name: {{project_name}}
description: A new Flutter project.
homepage: https://{{organization_name}}.{{domain_name}}
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^1.0.2
  cupertino_icons: ^1.0.2{{#analytics}}
  firebase_analytics: ^8.0.1
  firebase_core: ^1.0.4{{/analytics}}
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^2.0.0
  intl: ^0.17.0
  provider: ^5.0.0
  rx_bloc: ^2.0.0
  rxdart: ^0.26.0

dev_dependencies:
  auto_route_generator: ^1.0.2
  build_runner: ^1.12.2
  # flutter_driver:
  #   sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  rx_bloc_generator: ^3.0.2
  rx_bloc_test: ^2.0.0
  test: ^1.16.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

